FROM node:14.17.1

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ENV PORT=8080 \
    MONGO_USER=raj \
    MONGO_PASSWORD=EvlYbfEtt2QJ889N \
    MONGO_DEFAULT_DATABASE=formula1 \
    STRIPE_KEY=sk_test_51L031mSJ7QIBp9YogCokzS0YWES7psv3xAEDquDgI2NCm5GeCLbTa2iMKpZJncPLdwlFDBxu8Mo0tDsBaAoqdDRq00vxnq9ZKB \
    EMAIL_SERVICE=Outlook365 \
    EMAIL_HOST=outlook.office365.com \
    EMAIL_PORT=995 \
    EMAIL_ID=dev.magneto@outlook.com \
    EMAIL_PASS=bravoSix@141

EXPOSE 8080

CMD [ "npm", "run", "start-server" ]