name: Node.js CD staging

on:
  push:
    branches: ["master", "staging"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref_name == "master"
      environment: master
    if: github.ref_name == "staging"
      environment: staging

    strategy:
      matrix:
        node-version: [16.17]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci
      - run: npm run start-sever

      - name: Render Deployment
        uses: sws2apps/render-deployment@v1.1.0
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
