name: Node.js CD master

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:

    runs-on: ubuntu-latest
    environment: formula1-backend-production

    strategy:
      matrix:
        node-version: [16.17]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run start-sever
    - name: Render Deployment
      uses: sws2apps/render-deployment@v1.1.0
      with:
          serviceId: 'srv-cee60i9a6gdgn584usm0'
          apiKey: 'rnd_WevPROz8Zcnm9ePfCos9PX5PpHd7'
