name: Node.js CI master

on:
  pull_request:
    branches: [ "master" ]

jobs:
  pull_request:

    runs-on: ubuntu-latest
    environment: production

    strategy:
      matrix:
        node-version: [16.17]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run start-sever
